spring:
  #db setting
  datasource:
    url: jdbc:oracle:thin:@192.168.10.120:1521/xe
#    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: jude
    password: 12345
    driver-class-name: oracle.jdbc.OracleDriver

server:
  port: 8080
