spring:
  #db setting
  datasource:
    url: jdbc:oracle:thin:@192.168.10.120:1521/xe
#    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: jude
    password: 12345
    driver-class-name: oracle.jdbc.OracleDriver
  servlet:
    multipart:
      enabled: true
      max-file-size: 11MB
      max-request-size: 11MB
server:
  port: 8080

jwt:
  secret: jwtscretkey


#mybatis setting
mybatis:
  type-aliases-package: com.malgn.mission2.domain/**
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
#mybatis setting end

#file upload location
property:
  image:
    location: /Documents/mission2/uploadedImages/
    temp-location: /Documents/mission2/temp  